integration: add a test illustrating rust list implementation with corrupted client dir
Summary:
If a user has a missing client directory (manually removed, botched `eden rm`), `eden list` can fail in the following way:

```
┌─[helsel@devvm23248] - [~/eden_list_os_err/fbcode] - [Thu Apr 09, 14:54]
└─[$]> edenfsctl list
Error: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```

This is because `get_mounts()` treated every `config.json` entry as valid and immediately parsed `clients/<name>/config.toml`. If that per-client state directory was manually deleted, one `ENOENT` aborted the whole command.

This diff adds a test illustrating the issue

Differential Revision: D100238864

fbshipit-source-id: 11d4ce4335a3c8a690a7ed3856b54a8307327cb3