Enable smallvec "write" feature
Summary:
Required by buck2.

Found while working on {D102213623}.

```lang=log,counterexample
error[E0277]: the trait bound `SmallVec<[u8; 60]>: std::io::Write` is not satisfied
   --> fbcode/buck2/app/buck2_miniperf/src/linux.rs:129:52
    |
129 |     bincode::serde::encode_into_std_write(&output, &mut buff, bincode::config::legacy())
    |     -------------------------------------          ^^^^^^^^^ the trait `std::io::Write` is not implemented for `SmallVec<[u8; 60]>`
    |     |
    |     required by a bound introduced by this call
    |
note: required by a bound in `bincode::serde::encode_into_std_write`
   --> third-party/rust/vendor/bincode-2.0.1/src/features/serde/ser.rs:66:58
    |
 66 | pub fn encode_into_std_write<E: Serialize, C: Config, W: std::io::Write>(
    |                                                          ^^^^^^^^^^^^^^ required by this bound in `encode_into_std_write`
```

Reviewed By: vitaut

Differential Revision: D102236221

fbshipit-source-id: b5b328676fef69e3178831ba6cd6da8047133007