cli: fix eden list to handle missing client directories
Summary:
If a user has a missing client directory (manually removed, botched `eden rm`), `eden list` can fail in the following way:

```
┌─[helsel@devvm23248] - [~/eden_list_os_err/fbcode] - [Thu Apr 09, 14:54]
└─[$]> edenfsctl list
Error: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```

This is because `get_mounts()` treated every `config.json` entry as valid and immediately parsed `clients/<name>/config.toml`. If that per-client state directory was manually deleted, one `ENOENT` aborted the whole command.

This diff makes it so we dont crash.

Note that eden list output for this case is slightly different between Rust and Python. Rust marks it as unconfigured and Python doesn't. This diff is just meant to address the crash.

Reviewed By: zzl0

Differential Revision: D100237150

fbshipit-source-id: f66e39501607070428ba93b23e6ae9b091eecfdd